
version: '3'
services:
  app:
    build: .
    environment:
      - PORT=8080
      - NODE_ENV=development
      - ENV_NAME=local
    ports:
      - "5000:5000"
    volumes:
    - ./src:/opt/app/src
