FROM mhart/alpine-node:8
WORKDIR /app
COPY package.json /app
COPY yarn.lock /app
RUN yarn install
COPY webpack.config.js /app

FROM mhart/alpine-node:base-8
WORKDIR /app
COPY . /app
EXPOSE 8443
CMD npm run start-docker
